In [1]:
import os
import numpy as np
import pandas as pd
import sys

In [2]:
print(pd.__version__)
print(np.__version__)

2.3.3
1.26.4

In [3]:
print(sys.executable)

C:\Users\PANKAJ SHARMA\anaconda3\envs\ml_clean\python.exe

In [4]:
df = pd.read_csv(r"D:\desktop\ML\Machine Learning\Supervised ML\Naive bayes\SMSSpamCollection", sep='\t'
                     )
df

,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
0,ham,Ok lar... Joking wif u oni...
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...
2,ham,U dun say so early hor... U c already then say...
3,ham,"Nah I don't think he goes to usf, he lives aro..."
4,spam,FreeMsg Hey there darling it's been 3 week's n...
...,...,...
5566,spam,This is the 2nd time we have tried 2 contact u...
5567,ham,Will ü b going to esplanade fr home?
5568,ham,"Pity, * was in mood for that. So...any other s..."
5569,ham,The guy did some bitching but I acted like i'd...
5570,ham,Rofl. Its true to its name

In [5]:
df = pd.read_csv(r"D:\desktop\ML\Machine Learning\Supervised ML\Naive bayes\SMSSpamCollection", sep='\t',
                      names =["Label", "Messages"])
df

     Label                                           Messages
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
df.shape

(5572, 2)

In [7]:
df.isnull().sum()

Label       0
Messages    0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Label     5572 non-null   object
 1   Messages  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [9]:
df['Label'].unique()

array(['ham', 'spam'], dtype=object)

In [10]:
#df['Label'].value_counts()/len(df)*100
df['Label'].value_counts()

Label
ham     4825
spam     747
Name: count, dtype: int64

In [11]:
ham = df[df['Label']=='ham']
spam = df[df['Label']=='spam']

In [12]:
print(ham.shape, spam.shape)

(4825, 2) (747, 2)

In [13]:
# Upsample minority class, This is oversampling the minority class
spam = spam.sample(ham.shape[0], replace=True)

In [14]:
print(ham.shape, spam.shape)

(4825, 2) (4825, 2)

In [15]:
data = pd.concat([ham, spam], ignore_index=True)
data.shape

(9650, 2)

# Shuffle After Concatenation (Very Important)
- Right now:
- All ham rows first
- All spam rows later
- Model may see structured ordering.

In [16]:
data = data.sample(frac=1, random_state=42).reset_index(drop=True)
# .sample()? It randomly selects rows from a DataFrame.
# frac=1 means take 100% of rows,but in random order

In [17]:
data.tail()

     Label                                           Messages
9645  spam  Ur cash-balance is currently 500 pounds - to m...
9646  spam  URGENT!! Your 4* Costa Del Sol Holiday or £500...
9647  spam  Well done ENGLAND! Get the official poly ringt...
9648   ham  Just buy a pizza. Meat lovers or supreme. U ge...
9649  spam  WELL DONE! Your 4* Costa Del Sol Holiday or £5...

In [18]:
data['Label'].value_counts()

Label
ham     4825
spam    4825
Name: count, dtype: int64

# Data Cleaning part

In [19]:
# !pip install nltk
import re
import nltk
nltk.download('stopwords')
# stopwords: nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\PANKAJ
[nltk_data]     SHARMA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [21]:
ps = PorterStemmer()

stop_words = set(stopwords.words('english'))
print(stop_words)

{'my', 'having', "you've", 'only', "they'd", 'up', 'under', 'same', 'hers', 'you', 'mustn', 'haven', 'and', 'does', "i'll", 'no', 'hadn', "should've", 'above', "aren't", 'themselves', "shan't", "they're", 'wasn', 'had', 'now', "you'd", "it's", "i've", 'in', 'ain', 'this', 'those', 'after', "didn't", 'yourselves', 'against', 'mightn', 'because', 'couldn', 'y', 'more', "it'd", 'don', 'below', 'before', 'been', 't', "won't", 'out', 'they', 'm', "we've", "that'll", 'be', 'i', "couldn't", 'into', 'few', 'all', 'were', 'him', 'when', 'own', 'yourself', 'it', 'theirs', "you'll", "mightn't", 've', "it'll", "don't", 'is', 'such', 'she', 'what', 'hasn', 'ma', "he's", "she's", 'through', "she'll", 'once', 'won', 'on', "i'm", 'most', 'to', 'ours', 'that', 'he', 'the', "needn't", 'why', 'have', 'other', 'do', 'any', "hadn't", 'whom', 'where', 'these', 'being', 'will', 'during', 'a', 'from', 'did', "haven't", 'itself', 're', "they've", 'too', 'shouldn', "shouldn't", 'its', 'our', 'who', 'until', 'there', 'which', "weren't", 'while', 'very', 'was', 'for', 'his', 'so', "isn't", 'them', 's', 'by', 'needn', 'an', "she'd", 'between', "wouldn't", "you're", 'didn', "wasn't", 'both', "i'd", 'shan', 'we', 'over', 'can', 'wouldn', 'down', "he'd", 'myself', 'her', 'me', 'how', 'than', 'with', 'off', "he'll", 'of', 'but', "we're", "we'll", 'weren', 'am', 'himself', 'o', 'should', 'their', "doesn't", 'not', "mustn't", "they'll", 'nor', 'd', 'ourselves', "we'd", 'again', 'further', 'about', 'are', 'aren', 'just', 'doesn', 'as', 'your', 'isn', 'some', 'each', 'doing', 'herself', 'at', 'yours', 'here', 'or', 'then', 'if', 'll', 'has', "hasn't"}

In [22]:
corpus = []

for text in data['Messages']:
    review = re.sub('[^a-zA-Z]',' ', text)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stop_words]
    review = ' '.join(review)
    corpus.append(review)

# ps = PorterStemmer():  creates a stemming object used to reduce words to their root form to reduce vocabulary size and improve generalization.

| Original Word | Stemmed Output |
| ------------- | -------------- |
| playing       | play           |
| played        | play           |
| plays         | play           |
| studies       | studi          |
| running       | run            |

In [23]:
print(corpus)

['rememb', 'life mean lot love life love peopl life world call friend call world ge', 'e admin build might b slightli earlier call u reach', 'sorri went bed earli nightnight', 'import custom servic announc premier', 'free rington repli real', 'guarante latest nokia phone gb ipod mp player prize txt word collect tc llc ny usa p mt msgrcvd', 'nice day impress sensibl went home earli feel fine bore rememb', 'marvel mobil play offici ultim spider man game ur mobil right text spider game send u free ball wallpap', 'kindli send one flat lt decim gt today', 'hey darlin pick u colleg u tell wen mt love pete xx', 'collect valentin weekend pari inc flight hotel prize guarante text pari www rtf sphost com', 'fyi gonna call sporad start like lt gt bc doin shit', 'realli tot ur paper end long ago wat u copi ju got use u happi lar still haf studi', 'know pl open back', 'wake sinc check stuff saw true avail space pl call embassi send mail', 'jokin lar depend phone father get lor', 'free msg rington http tm widel com index wml id b ecef ff first true jul', 'u select stay top british hotel noth holiday valu dial claim nation rate call bx sw ss', 'hi jon pete ive bin spain recent hav sum dinero left bill said u ur rent mayb interest hav pe around tb jame', 'nokia tone ur mob everi week txt nok st tone free get txtin tell ur friend p tone repli hl info', 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap', 'free entri weekli comp send word enter c www textcomp com cust care', 'privat account statement xxxxxx show un redeem point call identifi code expir', 'poor girl go one day lmao', 'wanna get laid nite want real dog locat sent direct ur mobil join uk largest dog network txt park nyt ec lp msg', 'contract mobil mnth latest motorola nokia etc free doubl min text orang tariff text ye callback remov record', 'ur chanc win wkli shop spree txt shop c www txt shop com custcar x p wk', 'want new video phone anytim network min half price line rental free text month repli call free deliveri', 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss', 'knock knock txt whose enter r weekli draw gift voucher store yr choic cs www tkl com age stoptxtstop week', 'wan win meet greet westlif u current tour unbreak untam unkempt text cost p std text', 'send naughti pix', 'say bold torch later one torch bold', 'meet da call', 'free st week entri textpod chanc win gb ipod cash everi wk txt pod ts cs www textpod net custcar', 'lip sync shangela', 'u secret admir look make contact u find r reveal think ur special call', 'know u u know send chat let find p msg rcvd hg suit land row w j hl ldn year', 'burger king wanna play footi top stadium get burger king st sept go larg super coca cola walk winner', 'today voda number end select receiv award match pleas call quot claim code standard rate app', 'awesom text restock', 'take derek amp taylor walmart back time done leav mous desk text priscilla readi', 'oh k placement ah', 'yeah sure thing mate haunt got stuff sort im go sound anyway promot hex way dont know number joke', 'took hooch walk toaday fell splat graze knee everyth stay home see tomorrow', 'haha think', 'come onlin today night', 'ask mobil chatlin inclu free min india cust serv sed ye l er got mega bill dont giv shit bailiff due day want', 'home n readi', 'somewher beneath pale moon light someon think u dream come true goodnit amp sweet dream', 'ok wif co like tri new thing scare u dun like mah co u said loud', 'natali f invit friend repli ye see www sm ac u natali k stop send stop frnd', 'enjoy jamster videosound gold club credit new videosound logo musicnew get fun jamster co uk help call', 'let know need anyth els salad desert someth mani beer shall get', 'privat account statement show un redeem point call identifi code expir', 'miss', 'import inform orang user xxxxxxx today lucki day find log onto http www urawinn com fantast surpris await', 'hello thanx take call got job start monday', 'way', 'motiv behind everi dark shine light wait find behind everi best friend alway trust love bslvyl', 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free', 'sm auction nokia get win free auction take part send nokia hg suit land row w jhl', 'prize go anoth custom c www c biz p min polo ltd suit london w j hl pleas call back busi', 'love night wake see messag hope smile know great morn', 'u win music gift voucher everi week start txt word draw tsc www idew com skillgam winaweek age ppermesssubscript', 'got take take part wrc ralli oz u lucozad energi text ralli le p see pack lucozad co uk wrc itcould u', 'like tell deepest darkest fantasi call p min stop text call nat rate', 'cant pick phone right pl send messag', 'sexi sexi cum text im wet warm readi porn u fun msg free recd msg p inc vat cancel text stop', 'otherwis part time job na tuition', 'k best congrat', 'messag import inform user today lucki day find log onto http www urawinn com fantast surpris await', 'refus loan secur unsecur get credit call free text back help', 'babe lost', 'nope sinc ayo travel forgotten guy', 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar', 'themob hit link get premium pink panther game new sugabab crazi zebra anim badass hoodi wallpap free', 'abl sleep', 'dear xxxxxxx u invit xchat final attempt contact u txt chat p msgrcvdhg suit land row w j hl ldn yr', 'sir wait call', 'hope pee burn tonit', 'privat account statement show un redeem point call identifi code expir', 'safe trip nigeria wish happi soon compani share moment', 'sppok ur mob halloween collect nokia logo pic messag plu free eeri tone txt card spook', 'alright see bit', 'pl send comprehens mail pay much', 'tag friend seem count friend', 'ou guarante latest nokia phone gb ipod mp player prize txt word collect ibhltd ldnw h p mtmsgrcvd', 'goodmorn grandfath expir leav today', 'r u sam p eachoth meet go hous', 'oki', 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker', 'custom place call', 'ok', 'nah think goe usf live around though', 'guarante award mayb even cash claim ur award call free legitimat efreefon number wat u think', 'lastest stereophon marley dizze racal libertin stroke win nookii game flirt click themob wap bookmark text wap', 'pdate doubl min txt orang tariff latest motorola sonyericsson nokia bluetooth free call mobileupd call optout yhl', 'new tone week includ mcfli ab sara jorg shock smith switch order follow instruct next messag', 'k k pa lunch aha', 'k leav soon littl', 'lt gt min stop somewher first', 'urgent mobil award bonu caller prize nd attempt contact call box qu', 'urgent costa del sol holiday await collect call toclaim sae tc pobox stockport sk xh cost pm max min', 'check head drop stuff', 'freemsg hi babi wow got new cam mobi wanna c hot pic fanci chat im w utxt rpli chat hlp msg p rcv', 'join uk horniest dog servic u sex nite sign follow instruct txt entri nyt ec lp msg p', 'thank love torch bold', 'time ur flight tmr', 'free st week nokia tone ur mob everi week txt nokia get txting tell ur mate www getz co uk pobox w wq norm p tone', 'interflora late order interflora flower christma call place order midnight tomorrow', 'beauti truth graviti read care heart feel light someon feel heavi someon leav goodmorn', 'hi mandi sullivan call hotmix fm chosen receiv easter prize draw pleas telephon claim prize transfer someon els', 'import custom servic announc call freephon', 'boo thing back home littl bore alreadi', 'free msg rington http tm widel com index wml id b ecef ff first true jul', 'privat account statement show un redeem point call identifi code xx expir', 'want new nokia colour phone deliv tomorrow free minut mobil free text free camcord repli call', 'twink bear scalli skin jock call miss weekend fun call p min stop text call nat rate', 'gimm lt gt minut ago', 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg', 'howz pain hope u r fine', 'k sure consent form v', 'dare chang ring', 'turn stereo love mi phone unknown album', 'free messag thank use auction subscript servic p msgrcvd skip auction txt unsubscrib txt stop customercar', 'differ style', 'that cool want pleas', 'nd time tri contact u u pound prize claim easi call p per min bt nation rate', 'jay told alreadi', 'saturday sunday holiday difficult', 'send content page', 'guarante award mayb even cash claim ur award call free legitimat efreefon number wat u think', 'freemsg feelin kinda lnli hope u like keep compani jst got cam mobi wanna c pic txt repli date msg p rcv hlp stop', 'surf onlin store offer want buy thing', 'urgent mobil number bonu caller prize nd attempt reach call asap box n qp ppm', 'go take bath ill place key window', 'check choos babe video sm shsex netun fgkslpopw fgkslpo', 'privat account statement show unredeem bonu point claim call identifi code expir', 'urgent mobil number award prize guarante call land line claim valid hr', 'surli ill give come review', 'dear voucher holder claim week offer pc go http www e tlp co uk expressoff ts cs appli stop text txt stop', 'wherr boytoy', 'u subscrib best mobil content servic uk per ten day send stop helplin', 'didnt complet gist oh', 'someon u know ask date servic contact cant guess call reveal po box wu', 'hey babe go ever figur go new year', 'u win music gift voucher everi week start txt word draw tsc www ldew com skillgam winaweek age ppermesssubscript', 'wife knew time murder exactli', 'u r winner u ave special select receiv cash holiday flight inc speak live oper claim p min', 'summer final fanci chat flirt sexi singl yr area get match repli summer free join optout txt stop help', 'eeri nokia tone u rpli tone titl eg tone dracula titl ghost addamsfa munster exorcist twilight www getz co uk pobox w wq p', 'go write msg put dictionari mode cover screen hand press lt gt gentli remov ur hand interest', 'complimentari star ibiza holiday cash need urgent collect landlin lose box sk wp ppm', 'urgent pleas call landlin complimentari lux costa del sol holiday cash await collect ppm sae cs jame eh rr', 'swhrt u dey hope ur ok tot u day love n miss take care', 'tb persolvo chase us sinc sept definit pay thank inform ignor kath manchest', 'urgent call landlin complimentari tenerif holiday cash await collect sae cs box hp yf ppm', 'hi sexychat girl wait text text great night chat send stop stop servic', 'siva hostel aha', 'v skint fanci bevi waz gona go meet othr spoon jst bin watchng planet earth sofa v comfey dont make hav gd night', 'premium phone servic call', 'valu custom pleas advis follow recent review mob award bonu prize call', 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p', 'could seen recognis face', 'lyricalladi f invit friend repli ye see www sm ac u hmmross stop send stop frnd', 'new textbuddi chat horni guy ur area p free receiv search postcod gaytextbuddi com txt one name', 'fran decid go n e way im complet broke knacker got bout c u mrw love janx p dad fone credit', 'master buy bb co sale bf', 'dont use hook', 'sell ton coin sell coin someon thru paypal voila money back life pocket', 'ur award citi break could win summer shop spree everi wk txt store skilgm tsc winawk age perwksub', 'anyway go gym whatev love smile hope ok good day babe miss much alreadi', 'urgent tri contact u today draw show prize guarante call land line claim valid hr', 'dhoni luck win big titl win', 'made eta taunton plan hope still okday good see xx', 'pleas call immedi urgent messag wait', 'im good think', 'oki', 'ft good combin', 'pick receipt someth earlier', 'realli need kiss u miss u babi ur babi eva', 'privat account statement show un redeem point call identifi code expir', 'urgent mobil number award prize guarante call land line claim valid hr ppm', 'today offer claim ur worth discount voucher text ye savamob member offer mobil cs sub unsub repli x', 'bloomberg messag center wait appli futur http career bloomberg com', 'privat account statement', 'even friend priest call', 'uncl abbey happi new year abiola', 'pleas protect e threat sib never ask sensit inform like password atm sm pin thru email never share password anybodi', 'hi happi birthday hi hi hi hi hi hi hi', 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl', 'u r winner u ave special select receiv cash holiday flight inc speak live oper claim p min', 'urgent mobil xxx bonu caller prize nd attempt reach call asap box n qp ppm', 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info', 'hey charl sorri late repli', 'win urgent mobil number award prize guarante call land line claim valid hr ppm', 'yup havent want go yoga call book', 'yet chikku go room nw bu', 'yeah leav coupl minut amp let know get mu', 'latest news polic station toilet stolen cop noth go', 'much buzi', 'privat account statement show un redeem point call identifi code xx expir', 'messag free welcom new improv sex dog club unsubscrib servic repli stop msg p', 'prepar pound everi night', 'told hr want post chennai work', 'sppok ur mob halloween collect nokia logo pic messag plu free eeri tone txt card spook', 'free day sexi st georg day pic jordan txt pic dont miss everi wk sauci celeb pic c pocketbab co uk wk', 'import inform orang user xxxxxxx today lucki day find log onto http www urawinn com fantast surpris await', 'head straight', 'send resum', 'ard like dat lor juz meet mrt station dun haf come', 'rcv msg chat svc free hardcor servic text go u get noth u must age verifi yr network tri', 'hope good week check', 'dear voucher holder next meal us use follow link pc enjoy dine experiencehttp www vouch com etlp dine asp', 'pay first lar da stock comin', 'dont forget place mani free request stchoic co uk wish inform call', 'u look da lib got stuff havent finish yet', 'bore housew chat n date bt nation rate p min landlin', 'text pass collect polyphon rington normal gpr charg appli enjoy tone', 'releas anoth italian one today cosign option', 'hot n horni will live local text repli hear strt back p per msg netcollex ltdhelpdesk repli stop end', 'wanna get laid nite want real dog locat sent direct ur mobil join uk largest dog network txt park nyt ec lp msg', 'u haf keep busi', 'cashbin co uk get lot cash weekend www cashbin co uk dear welcom weekend got biggest best ever cash give away', 'yep great loxahatche xma tree burn lt gt start hour', 'well watch shrek b', 'miss call alert number call left messag', 'recpt order rington order process', 'new club dont fink met yet b gr c u pleas leav msg day wiv ur area repli promis carli x call minmobsmor lkpobox hp fl', 'unsubscrib servic get ton sexi babe hunk straight phone go http gotbab co uk subscript', 'remind get pound free call credit detail great offer pl repli text valid name hous postcod', 'camera award sipix digit camera call fromm landlin deliveri within day', 'ever thought live good life perfect partner txt back name age join mobil commun p sm', 'ye place town meet excit adult singl uk txt chat p msg', 'polyphon tone ur mob everi week txt pt st tone free get txtin tell ur friend p tone repli hl info', 'get garden readi summer free select summer bulb seed worth scotsman saturday stop go notxt co uk', 'hi chachi tri call u unabl reach u pl give miss cal u c tiz msg kanagu', 'pleas call immedi urgent messag wait', 'date servic ask contact u someon shi call reveal pobox uz p', 'flirt txt girl bloke ur name age eg girl zoe join get chat', 'send yetti number pl', 'hot live fantasi call p per min ntt ltd po box croydon cr wb k', 'thank rington order refer number x mobil charg tone arriv pleas call custom servic colour red text colour txtstar', 'okmail dear dave final notic collect tenerif holiday cash award call landlin tc sae box cw wx ppm', 'sent send', 'remain unconvinc elabor test willpow', 'ye last practic', 'ok happen behav like', 'nokia get win free auction take part send nokia hg suit land row w jhl', 'hello r u im bore inev thought id get bore tv tell someth excit happen anyth', 'still mayb leav credit card get ga get back like told', 'rt king pro video club need help info ringtonek co uk call must club credit redeem www ringtonek co uk enjoy', 'never believ actual got taunton wow', 'anyth lor u decid', 'alway chat fact need money rais', 'yeah probabl still gotta check leo', 'opinion jada kusruthi lovabl silent spl charact matur stylish simpl pl repli', 'hello boytoy geeee miss alreadi woke wish bed cuddl love', 'kit strip bill p netcollex ltd po box ig oja', 'see finish load loan pay', 'cashbin co uk get lot cash weekend www cashbin co uk dear welcom weekend got biggest best ever cash give away', 'goal arsen henri v liverpool henri score simpl shot yard pass bergkamp give arsen goal margin min', 'ok would b love u r sure think wot u want drinkin dancin eatin cinema u wot', 'u secret admir look make contact u find r reveal think ur special call', 'room', 'congratul thank good friend u xma prize claim easi call p per minut bt nation rate', 'sac score big hundr set batsman', 'privat account statement show unredeem bonu point claim call identifi code expir', 'say lt gt year old man money last lt gt still wait check', 'realiz year thousand old ladi run around tattoo', 'know result', 'nah perpetu dd', 'great role model give much realli wish day miracl god reason everyth must say wish knew dont look sinc young still great day', 'go jurong point crazi avail bugi n great world la e buffet cine got amor wat', 'chang fb jaykwon thuglyf falconerf', 'love start attract feel need everi time around first thing come thought would start day end everi time dream love everi breath name life happen around life name would cri give happi take sorrow readi fight anyon love craziest thing love proov anyon girl beauti ladi whole planet alway sing prais love start make chicken curri end maki sambar life beauti get everi morn thank god day would like say lot tell later', 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi', 'come peopl', 'haha figur well found piec priscilla bowl', 'dunno juz askin co got card got salon call hair sens tot da one cut ur hair', 'next month get upto call ur standard network charg activ call c wire net st term pobox uz cost min mobcudb', 'custom servic annonc new year deliveri wait pleas call arrang deliveri', 'messag free welcom new improv sex dog club unsubscrib servic repli stop msg p', 'lol well without could big sale togeth', 'free tarot text find love life tri free text chanc free msg', 'dunno lei thk mum lazi go neva ask yet', 'hey elain today meet still', 'dunno lei like dun haf', 'xma reward wait comput randomli pick loyal mobil custom receiv reward call', 'cool text head', 'sent ur email id soon', 'gorgeou keep pix cum thank', 'storm msg wen u lift phne u say hello u knw wt real mean hello name girl ye u knw dat girl margaret hello girlfrnd f grahmbel invnt telphon moral one get name person bt girlfrnd g n g h', 'yeah tri scroung someth', 'messag great doctor india drink appi fizz contain cancer caus age', 'thank princess want see nice juici booti', 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw', 'class hour sorri', 'cant think anyon spare room top head', 'get brand new mobil phone agent mob plu load goodi info text mat', 'home watch tv lor', 'id onluy matter get offcampu', 'see shadow get earli spring yay', 'tb persolvo chase us sinc sept definit pay thank inform ignor kath manchest', 'watch lotr w si di aft u wan meet dinner nite', 'remind download content alreadi paid goto http doit mymobi tv collect content', 'offic around pm go hospit', 'free tone hope enjoy new content text stop unsubscrib help p provid tone co uk', 'ok april cant wait', 'lost pound help', 'take care n get well soon', 'pay like lt gt 

In [24]:
len(corpus)

9650

In [25]:
len(corpus[1000])

76

# Bag of words

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
#x_bow = cv.fit_transform(corpus).toarray()

In [27]:
x_bow = cv.fit_transform(corpus)

In [28]:
x_bow.shape

(9650, 6296)

In [29]:
type(x_bow)

scipy.sparse._csr.csr_matrix

In [30]:
x_bow[500].shape
# length of every row
# 6295 is vocabulary size

(1, 6296)

In [31]:
#print(x_bow)

In [32]:
data.head()

  Label                                           Messages
0   ham            So what about you. What do you remember
1   ham  My life Means a lot to me, Not because I love ...
2   ham  E admin building there? I might b slightly ear...
3   ham               Sorry, went to bed early, nightnight
4  spam  You have an important customer service announc...

In [33]:
data['Label'] = data['Label'].astype('category')
data['Label'] = data['Label'].cat.codes

In [34]:
data.shape

(9650, 2)

In [35]:
data[['Label']]

      Label
0         0
1         0
2         0
3         0
4         1
...     ...
9645      1
9646      1
9647      1
9648      0
9649      1

[9650 rows x 1 columns]

In [36]:
# split the data into training and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_bow, data['Label'], test_size=0.30, random_state=42,stratify = data['Label'])

In [37]:
#print(x_train)

In [38]:
x_test

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 30584 stored elements and shape (2895, 6296)>

In [39]:
y_train

2838    1
4160    1
4112    1
6674    1
6540    1
       ..
6959    1
6731    0
983     0
532     0
7775    0
Name: Label, Length: 6755, dtype: int8

In [40]:
y_test

5427    1
2164    0
8047    0
8586    1
1484    0
       ..
6196    1
2782    1
8644    0
2386    1
991     0
Name: Label, Length: 2895, dtype: int8

# Building Niave Bayes Theorem

In [41]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB

param_grid = {'alpha': [0.01, 0.1, 0.5, 1.0, 2.0]}

nb_model_grid = GridSearchCV(MultinomialNB(), param_grid,scoring='f1', cv=5)
nb_model_grid.fit(x_train, y_train)

print(nb_model_grid.best_params_)

{'alpha': 0.01}

In [42]:
best_model = nb_model_grid.best_estimator_

In [43]:
y_pred_train = best_model.predict(x_train)
y_pred_test = best_model.predict(x_test)

In [44]:
y_pred_test

array([1, 0, 0, ..., 0, 1, 0], dtype=int8)

In [45]:
y_pred_train

array([1, 1, 1, ..., 0, 0, 0], dtype=int8)

# Evaluation

In [46]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [47]:
print(confusion_matrix(y_train, y_pred_train))
print()
print(confusion_matrix(y_test, y_pred_test))

[[3317   60]
 [  21 3357]]

[[1417   31]
 [  10 1437]]

In [48]:
print(classification_report(y_train, y_pred_train))
print()
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      3377
           1       0.98      0.99      0.99      3378

    accuracy                           0.99      6755
   macro avg       0.99      0.99      0.99      6755
weighted avg       0.99      0.99      0.99      6755


              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1448
           1       0.98      0.99      0.99      1447

    accuracy                           0.99      2895
   macro avg       0.99      0.99      0.99      2895
weighted avg       0.99      0.99      0.99      2895

In [49]:
print(accuracy_score(y_train, y_pred_train))
print()
print(accuracy_score(y_test, y_pred_test))

0.9880088823094004

0.9858376511226252

# Step 1 — After Training, Create Prediction Function

In [50]:
import re

def preprocess_text(text):
    text = re.sub('[^a-zA-Z]', ' ', text)
    text = text.lower()
    text = text.split()
    text = ' '.join(text)
    return text

# Step 2 — Predict New Email

In [51]:
def predict_email(email_text):
    # Step 1: Clean
    cleaned_text = preprocess_text(email_text)

    # Step 2: Vectorize (transform only!)
    vector = cv.transform([cleaned_text])

    # Step 3: Predict
    prediction = best_model.predict(vector)[0]

    if prediction == 1:
        return "Spam"
    else:
        return "Ham"

# Example Usage

In [55]:
new_mail = "Hello PANKAJ SHARMA,Thank you for registering for PC AIML Machine Learning. You can find information about this meeting below.PC AIML Machine Learning"

print(predict_email(new_mail))

Spam

In [53]:
new_mail = "Hello! Pankaj can you come tomorrow for urgent meeting"

print(predict_email(new_mail))

Ham

In [54]:
new_mail = 'urgent tri contact u today draw show prize guarante call land line claim c valid hr'

print(predict_email(new_mail))

Spam

| Step               | Manual Cleaning | Vectorizer     |
| ------------------ | --------------- | -------------- |
| Lowercase          | Yes             | Yes            |
| Remove punctuation | Yes             | Yes            |
| Remove stopwords   | Yes             | Yes (optional) |
| Stemming           | Yes             | No             |
| Needed for BOW?    | ❌ No            |                |
| Needed for TF-IDF? | ❌ No            |                |

# While need to save the model you should use concept of pipe line